### ISSUE TITLE
Проектирование диаграммы сущностей БД 

### ISSUE THREAD

**Issue by serykhelena** [lsd-maddrive/qr_conveyor#14]
Нужно подготовить схему с диаграммой сущностей БД 

На диаграмме должны быть: 
- обозначения связей (по каким полям) таблицы между собой взаимодействуют
- указание Primary Key и Forign Key
- названия и тип колонок в таблицах
- названия самих таблиц 

Для рисования диаграммы можно использовать https://app.diagrams.net/

**Comment by mrGremlin2019** [comment]
[сущность БД.docx](https://github.com/lsd-maddrive/qr_conveyor/files/14639918/default.docx)

**Comment by mrGremlin2019** [comment]
Относительно функционала для телеграм-бота:
1.	Запрос информации о конкретном товаре:
Пользователь может отправить запрос на получение информации о товаре по его названию или ID.
2.	Поиск товаров по параметрам:
Возможность найти все товары определенного веса, размера или с указанным признаком хрупкости.
3.	Статистика о количестве отсканированных товаров:
Бот может предоставить графики или статистику о количестве отсканированных товаров за определенный период времени.
4.	Уведомления о новых поступлениях товаров:
Бот может отправлять уведомления о новых поступлениях товаров на склад.
5.	Поиск местоположения товара на складе:
Пользователь может запросить информацию о том, где находится конкретный товар на складе.
